# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TaboolaHomeAssignment' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'TaboolaSDK', '2.1.3'
  # Pods for TaboolaHomeAssignment

  target 'TaboolaHomeAssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
